version: "3.4"

services:
  api:
    build:
      context: .
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORT=https://+:81
      - ASPNETCORE_DB=Host=host.docker.internal;Port=5432;Database=minozas_catering_db;Username=postgres;Password=postgres;
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=minozas_catering_db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
    driver: local
